version: '3.8'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    hostname: sonarqube
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - $PWD/sonarqube_data:/opt/sonarqube/data
      - $PWD/sonarqube_extensions:/opt/sonarqube/extensions
      - $PWD/sonarqube_logs:/opt/sonarqube/logs
      - $PWD/sonarqube_temp:/opt/sonarqube/temp
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - $PWD/postgresql:/var/lib/postgresql
      - $PWD/postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  postgresql:
  postgresql_data:
